internal/pkg/admission/admission.go, internal/pkg/admission/policy-server-configmap.go, internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-secret.go
In case you want to enable `golangci-lint` for this project, feel free to use my config at https://github.com/romie-gr/romie/blob/master/.golangci.yml
=> Fix golangci-lint errors

README.md, api/v1alpha1/admissionpolicy_types.go, config/crd/bases/chimera.suse.com_admissionpolicies.yaml, config/generated/all.yaml, internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/policy-server-configmap.go, internal/pkg/admission/reconciler.go
Allow the definition of mutating policies
=> Add support for mutating policies

.github/workflows/container-image.yml
This repo still requires other changes, but this is an isolated one that should work fine.
=> Use `GITHUB_TOKEN` instead of a personal access token

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, CONTRIBUTING.md, Makefile
Fixes https://github.com/kubewarden/kubewarden-controller/issues/26
After this is merged, I will run this mechanism and create the initial CHANGELOG.md with a tagged release.
=> feat: add changelog generation tooling

RELEASE_NOTES/RELEASE_NOTES_v0.2.0.md
Add the release notes for v0.2.0
Fixes https://github.com/kubewarden/kubewarden-controller/issues/34
=> Add release notes for v0.2.0

internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/policy-server-secret.go, internal/pkg/admission/policy-server-secret_test.go, internal/pkg/admission/reconciler.go, internal/pkg/admission/validating-webhook.go, internal/pkg/constants/constants.go
Fixes kubewarden/kubewarden-controller#55
=> PolicyServer control loop: create root CA infrastructure

apis/policies/v1alpha2/policyserver_types.go, config/crd/bases/policies.kubewarden.io_policyservers.yaml, controllers/policies/clusteradmissionpolicy_controller.go, controllers/policies/policyserver_controller.go, internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/policy-server-configmap.go, internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-deployment_test.go, internal/pkg/admission/policy-server-secret.go, internal/pkg/admission/policy-server-secret_test.go, internal/pkg/admission/policy-server-service.go, internal/pkg/admission/reconciler.go, internal/pkg/admission/validating-webhook.go, internal/pkg/constants/constants.go, main.go
Fixes  kubewarden/kubewarden-controller#57
=>  PolicyServer control loop: create Policy Server Deployment

apis/policies/v1alpha2/policyserver_types.go, internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-service.go, internal/pkg/admission/reconciler.go, internal/pkg/constants/constants.go
Fixes kubewarden/kubewarden-controller#58
=>  PolicyServer control loop: create Policy Server Service

controllers/policies/policyserver_controller.go, internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/policy-server-configmap.go, internal/pkg/admission/policy-server-configmap_test.go, internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/reconciler.go, internal/pkg/admission/validating-webhook.go, internal/pkg/constants/constants.go
Fixes kubewarden/kubewarden-controller#59
=> PolicyServer control loop: watch ClusterAdmissionPolicies

Makefile, controllers/policies/clusteradmissionpolicy_controller.go, controllers/policies/policyserver_controller.go, internal/pkg/admission/reconciler.go, internal/pkg/admission/reconciler_test.go, internal/pkg/constants/constants.go, scripts/removeFinalizersFromCRDs.sh
Fixes kubewarden/kubewarden-controller#67
=> Add finalizers to our resources

CONTRIBUTING.md
Updates the CONTRIBUTING.md adding documentation about how to build the kubewarden-controller project.
=> Building instructions.

PROJECT, apis/policies/v1alpha2/policyserver_webhook.go, apis/policies/v1alpha2/webhook_suite_test.go, config/webhook/manifests.yaml, main.go
Fixes kubewarden/kubewarden-controller#70
=> Implement webhook for PolicyServer resource

.github/workflows/ci.yml, internal/pkg/admission/policy-server-error_test.go
fixes  kubewarden/kubewarden-controller#62
This is how it will look like after adding the status check: https://github.com/raulcabello/kubewarden-controller/pull/1 
I'll squash the commits before merging
=> Run tests for all branches in github actions 

.github/workflows/shellcheck.yml, scripts/removeFinalizersFromCRDs.sh, scripts/uninstall.sh, uninstall.sh
This script can be used as a last resort when `helm uninstall` doesn't work
=> Add uninstall script

internal/pkg/admission/policy-server_integration_test.go
fixes kubewarden/kubewarden-controller#89
=> Fix flaky test TestCAAndCertificateCreationInAHttpsServer

CONTRIBUTING.md
Co-authored-by: raulcabello <raul.cabello@suse.com>
=> docs: Don't forget to push main on release

.github/workflows/container-build.yml, .github/workflows/container-image.yml, .github/workflows/e2e-tests.yml
Adds a new workflow to run the Kubewarden end-to-end test every day.
Closes #132
=> Run end-to-end tests daily basis.

.github/workflows/ci.yml
Updates the ci.yml adding the configuration to allow other workflows call it to run the tests.
=> Turn ci.yml a callable workflow.

.github/workflows/e2e-tests.yml
Updates the workflow used to run the end-to-end tests to use the self-hosted runner.
=> Run e2e test in a self-hosted action runner.

.github/workflows/e2e-tests.yml
This reverts commit 90e3ea08aa6876fa7c3801c9d4f82a2e04f4e695.
=> Revert "Run e2e test in a self-hosted action runner."

.github/workflows/e2e-tests.yml
Updates the e2e tests version to v0.2.0. This version allow us to run the tests on self-hosted runners.
=> E2e test version

apis/policies/v1alpha2/clusteradmissionpolicy_types.go, apis/policies/v1alpha2/clusteradmissionpolicy_webhook.go, config/crd/bases/policies.kubewarden.io_clusteradmissionpolicies.yaml, docs/crds/README.asciidoc, internal/pkg/admission/policy-server-configmap.go
Depends on: https://github.com/kubewarden/policy-server/pull/194
Fixes: https://github.com/kubewarden/policy-server/issues/190
=> Implement monitor mode

controllers/policies/policyserver_controller.go
Kubewarden controller has a problem when the user delete a Cluster Admission
Policy. The controller tries to update the status of the old object of the
update event which adds the delete timestamp in the resource. This fails
because the old object is not the current version of the resource, causing a
conflict and a ugly stacktrace in the logs.
To solve this, this commit rewrite the functions used to watch such events and
changes the update event handler to change status only in the new object. As
well as moves the delete handler to a separate function.
Fix #136 
See the bug [description](https://github.com/kubewarden/kubewarden-controller/issues/136#issue-1076745997). There are example of how to simulate the issue.
=> Does not update the old object of an update event.

rfc/0003-policy-signing.md
Update the RFC to reflect the final design of the yml file
=> Update policy signing RFC

docs/crds/README.asciidoc
=> Add AdmissionPolicy to API Reference

CHANGELOG.md
Updates changelog to further release a new version
=> Updates CHANGELOG.md with v0.5.2 changes

internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-deployment_test.go
If the container of the policy server is not in the first position of the deployment container list, the policy server rollout does not start. This commit changes this behaviour by looking for the policy server container in any position of the container list.
Fix #178
=> Check the policy server container image in all containers. 

docs/crds/README.asciidoc
Update crd docs by running `make generate` under `crds/`.
=> docs: Update crd docs

CHANGELOG.md
Update Changelog to v1.0.0-rc1.
=> chore: Update CHANGELOG.md to v1.0.0-rc1

.github/workflows/container-image.yml
Use the shared GH action we created to install the bom utility.
=> GH action: use bom installer action

README.md
Fix https://github.com/kubewarden/kubewarden.io/issues/125
=> Add slack info to README.md

ADOPTERS.md
Signed-off-by: Olivier Vernin <olivier.vernin@suse.com>
I propose to add an ADOPTERS file to list organization who use Kubewarden 
/
Some organization ask to mention various information such as the size of Kubernetes clusters, or the size the of the organization. 
I would prefer to keep this list simple.
/
=> Init ADOPTERS.md

.github/workflows/e2e-tests.yml, README.md
=> Add E2E tests badge

README.md
=> Fix: add link to e2e status button

CHANGELOG.md
Create a RC1 for the new kubewarden release
=> v1.3.0 rc1

CHANGELOG.md
=> Tag v1.3.0-rc3

CHANGELOG.md
=> Tag v1.3.0

README.md
=> chore: Add FOSSA license scan badge

CHANGELOG.md
chore: Update CHANGELOG.md for 1.4.0
With e2e tests.
=> chore: Update CHANGELOG.md for 1.4.0

.github/release-drafter.yml
Relates to https://github.com/kubewarden/automation/pull/39
Part of the task of "label PRs automatically".
Needs to be merged for the changes in the PR to be effective on PR titles.
Buuut I'm gonna use this PR title to see if the autolabeler works.
=> fix: autolabeler of issues

README.md
Adds a section in the README.md file with information about the Kubewarden community meeting.
=> Community meeting documentation.

README.md
Signed-off-by: Akshit42-hue <patelakshit2025@gmail.com>
Since there are no details available for the meetings in the readme file. This would be helpful for new contributors/joiners
=> Added Community meeting details

.github/workflows/openssf.yml
This ought to fix https://github.com/kubewarden/kubewarden-controller/actions/runs/4859155915
=> deps: Bump GHA ossf/scorecard-action to v2.1.3

docs/crds/README.asciidoc
Updates the CRDs docs for the next release, version 1.7.0-rc1.
Related to https://github.com/kubewarden/kubewarden-controller/issues/473
=> Update docs for v1.7.0-rc1 release.

README.md
Update the README file formatting the style using the Prettier tool.
=> fix: formats README using Prettier.

.github/workflows/ci.yml, .github/workflows/container-image.yml, .github/workflows/fossa.yml, .github/workflows/openssf.yml, .github/workflows/release-drafter.yml, .github/workflows/release.yml, .github/workflows/sbom.yml, .github/workflows/sign-image.yml
Provide full version for GH actions
=> chore(deps): be explicit about the GH actions versions

internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-deployment_test.go, internal/pkg/constants/constants.go
Reverts kubewarden/kubewarden-controller#553
=> Revert "fix!: Don't reconcile KUBEWARDEN_LOG_FMT envvar"

ADOPTERS.md
=> chore: Typo in ADOPTERS.md

ADOPTERS.md
=> chore: Reword ADOPTERS.md

ADOPTERS.md
Thanks to @Martin-Weiss who got the approval from CLAAS.
=> Add CLAAS to the list of adopters

CONTRIBUTING.md
Adds in the CONTRIBUTING.md file a checklist with some steps to follow in a Kubewarden stack release. This checklist has some basic steps to avoid forgetting important updates that are required to a successful release.
=> chore(docs): Kubewarden release template.

CONTRIBUTING.md
Updates the release checklist adding some fields that must be verified before merging the changes in the Helm charts.
=> chore(doc): update checks for Helm chart updates

controllers/admissionpolicy_controller_test.go, controllers/clusteradmissionpolicy_controller_test.go, controllers/policyserver_controller_test.go, controllers/utils_test.go
Fix: #705 
Also, it cleans up and lints the integration tests for added clarity.
=> test: clean up integration tests

.github/workflows/ci.yml, pkg/apis/policies/v1/policyserver_webhook.go, pkg/apis/policies/v1/policyserver_webhook_test.go
=> fix:  PolicyServer field.ErrorList validation

CONTRIBUTING.md, Tiltfile, tilt-settings.yaml.example
Ensure the `PolicyReport` and `ClusterPolicyReport` CRDs are installed into the cluster.
=> Fix the local development with tilt

CONTRIBUTING.md, README.md, SECURITY.md, controllers/admissionpolicy_controller_test.go, controllers/policyserver_controller.go, controllers/suite_test.go, internal/pkg/admission/policy-server-error_test.go, internal/pkg/admissionregistration/cert.go, main.go, pkg/apis/policies/v1/admissionpolicy_types.go
I noticed a typo and one thing led to another. I hope you all don't mind me looking at docs, comments and strings here.
=> minor typos and other corrections

Makefile
Readd the Makefile target used to build the CRDs.
=> fix: add generate-crds target.

api/policies/v1/policy_types.go, config/crd/bases/policies.kubewarden.io_admissionpolicies.yaml, config/crd/bases/policies.kubewarden.io_clusteradmissionpolicies.yaml, config/crd/bases/policies.kubewarden.io_policyservers.yaml, docs/crds/CRD-docs-for-docs-repo.md
Relates to https://github.com/kubewarden/kubewarden-controller/pull/826
Check in result of doing `cd docs/crds; make generate`
NA
=> chore: Refresh CRD-docs-for-docs-repo.md

.github/workflows/release.yml
=> ci: Run golangcilint for go-version 1.22 

internal/certs/certs.go
=> fix: generate certificates with the same settings as helm helper functions

api/policies/v1/policygroup_validation.go, api/policies/v1/policygroup_validation_test.go
Updates the validation webhook for the policy groups types to validate the policies members names. This is necessary because the names are used as CEL functions names in the policy group expression. Therefore, they need to be compliant with the CEL syntax. The regex used to validate the name is based on the language definition:
https://github.com/google/cel-spec/blob/master/doc/langdef.md#syntax
Fix https://github.com/kubewarden/kubewarden-controller/issues/876
=> feat: validate policy group members names.

internal/controller/admissionpolicy_controller_test.go, internal/controller/admissionpolicygroup_controller_test.go, internal/controller/clusteradmissionpolicy_controller_test.go, internal/controller/clusteradmissionpolicygroup_controller_test.go
Related to #887, adds missing deletion tests.
=> test: add policy deletion -> webhook deletion tests

.github/workflows/govulncheck.yml, .github/workflows/sbom.yml
Fixing permission in govulncheck. This will fix part of the OpenSFF score card.
=> Fix gh workflow permissions

internal/controller/policyserver_controller_deployment.go, internal/controller/policyserver_controller_test.go
This reverts commit 2e07b8f1d7ecd8401fe1bafd41c44611c6b0bcfd.
The multiple CA changes has been merged in Policy Server code. Those are the missing changes that required us to add the "dropme" commit.
Related to #1000
=> Revert "dropme: green ci"

internal/controller/policyserver_controller_deployment.go
We always mount and configure the internal CA in the PolicyServer deployment.
This is incorrect because it causes the webhook endpoints to require certificates issued by the internal CA.
This PR fixes the issue by enabling the internal CA and mTLS communication with the audit scanner only when a client CA is provided.
=> fix: mount and configure internal CA only with mTLS enabled

internal/controller/policyserver_controller_service.go, internal/controller/policyserver_controller_test.go
Fix https://github.com/kubewarden/kubewarden-controller/issues/1052
Added a new test.
=> fix: Correctly set service labels
