Makefile
Otherwise it would warn about 'controller-gen' not in $PATH, which
is exactly what's being handled here.
=> Silence 'which'

controllers/cluster_admissionpolicy_controller.go, internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/reconciler.go, main.go
The policy-server can use the provided service account, so it can be
granted permissions to list certain resources that will be exposed to
context-aware policies.
Related: https://github.com/kubewarden/helm-charts/issues/4
A helm chart PR will follow that depends on this PR.
=> Allow to configure policy-server service account

.github/workflows/release.yml
This action will create a Github release whenever a tag `v<version>`
is pushed to the repository.
Image building and publishing into the image repository is still
handled by the `container-image` workflow.
Fixes https://github.com/kubewarden/kubewarden-controller/issues/22
=> Add Github release action

rfc/0001-policy-server-custom-resource.md
This RFC describes how we can change the current architecture to make the Kubewarden stack easier to configure and, at the same time, improve scalability and resiliency.
[Rendered link](https://github.com/flavio/kubewarden-controller/blob/policy-server-crd-proposal/rfc/0001-policy-server-custom-resource.md).
=> Add RFC about new architecture

internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-secret.go, internal/pkg/admission/policy-server-secret_test.go, internal/pkg/admission/policy-server-service.go, internal/pkg/admission/policy-server_integration_test.go, internal/pkg/admission/reconciler.go, internal/pkg/admission/validating-webhook.go, internal/pkg/admissionregistration/ca.go, internal/pkg/constants/constants.go
Fixes kubewarden/kubewarden-controller#56
I added an integration test that creates ca and policy server certs and validates them in a go https server. Right now it will also be executed with the unit tests when running go test ./... We can add a flag for the integration tests to run them separately as they take longer than the unit tests (this int test takes a bit more than 1 second in my machine). Maybe we don't need it now, but just keep it in mind for the future. What do you think?
=> PolicyServer control loop: create certificates for Policy Server deployment

internal/pkg/admission/policy-server-deployment.go
Fixes kubewarden/kubewarden-controller#71
=> Fix controller panic when policy server does not have any annotation

apis/policies/v1alpha2/clusteradmissionpolicy_types.go
This name is more in line to how other conditions are named in other core API resources.
=> Rename condition from `active` to `PolicyActive`

apis/policies/v1alpha2/clusteradmissionpolicy_types.go, docs/crds/README.asciidoc
Generate the file that holds the description of our CRD.
That was generated by using the `make generate` target inside of the `docs/crds` directory
=> Update the CRDs docs

internal/pkg/admission/policy-server-service.go, internal/pkg/admission/policy-server-service_test.go, internal/pkg/constants/constants.go
Related: https://github.com/kubewarden/policy-server/issues/106
- Add sample `otel-collector.yaml.example` file containing a basic
OpenTelemetry collector resource that can be deployed using the
OpenTelemetry operator.
- If metrics are enabled, expose metrics port on the policy-server
service, so a prometheus instance running on the cluster can be
instructed to scrape this endpoint.
=> feat: add OpenTelemetry integration

internal/pkg/admission/policy-server-configmap.go, internal/pkg/admission/policy-server-configmap_test.go, internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-secret.go, internal/pkg/admission/policy-server-secret_test.go, internal/pkg/admission/policy-server_integration_test.go, internal/pkg/admission/reconciler.go, internal/pkg/admission/reconciler_test.go
The GH Action for golangci-lint now uses golangci-lint v1.43.
This PR makes golangci-lint happy.
=> refactor: Fix golangci-lint 1.43 issues

internal/pkg/admission/policy-server-deployment.go, internal/pkg/constants/constants.go
Adds a new label in the policy servers deployment. The new label stores the name of the policy server which originates the deployment.
=> feat: policy server name label in the deployment.

CHANGELOG.md, CONTRIBUTING.md, Makefile
Drop `make tag`, use `git-chglog --next`, and reinstate old changelog entries.
Fixes https://github.com/kubewarden/kubewarden-controller/issues/119
=> Change git-chglog and CHANGELOG.md workflow

rfc/0002-report-mode.md
Fixes: https://github.com/kubewarden/kubewarden-controller/issues/126
What we have been calling "audit" mode in our issues is what this RFC describes. I think the name used in the RFC is closer to what we mean: "report" mode. A policy can be in "report" mode (what is described in this RFC) or in "enforce" mode (the only mode we have right now).
Audit was part of this RFC as well, but I wanted to split it so I can open another one with only Audit. In my opinion, Audit refers to the fact of auditing the existing state of the cluster, this is: checking that all resources that are persisted at this time are validated by all policies that target them.
=> Add Report Mode RFC

internal/pkg/admission/policy-server-deployment.go
Since https://github.com/kubewarden/policy-server/pull/138, the layout of the policy-server container image has been simplified.
Its current layout looks like:
- /etc/group
- /etc/passwd
- /policy-server
Given we don't have a LSB-based layout, make /tmp be mounted by the Kubewarden controller as an empty dir.
=> Mount /tmp as an empty dir to store policies

internal/pkg/admission/common_test.go, internal/pkg/admission/policy-server-configmap.go, internal/pkg/admission/policy-server-configmap_test.go, internal/pkg/admission/reconciler_test.go
Adds a new field in the configmap where the policies info are store. The new "Mutating" field tells Policy Server that the policy can mutate requests or not.
=>  Mutating field in the policy configmap

internal/pkg/admission/policy-server-deployment.go
Ensure the Policy Server container runs with a readonly root filesystem.
This improves the security of the project.
This partially addresses https://github.com/kubewarden/helm-charts/issues/51
=> fix(policy-server): Run the policy server with readonly root

.github/workflows/release.yml
If the tag contains '-alpha', '-beta' or '-rc' a release with the flag
pre-release will be created.
Fixes: https://github.com/kubewarden/kubewarden-controller/issues/143
=> Update GitHub release creation

rfc/0003-policy-signing.md
This is an RFC that describes how we can implement policy verification inside of Policy Server and kwctl.
[Rendered version](https://github.com/flavio/kubewarden-controller/blob/sigstore-integration-rfc/rfc/0003-policy-signing.md)
=> Add initial RFC about policy signing

rfc/0004-tests-arch.md
Adds a RFC proposing how the Kubewarden project should organize and run their tests.
Please, let me know if you miss some information in the RFC.
[Rendered](https://github.com/jvanz/kubewarden-controller/blob/test-arch/rfc/0003-tests-arch.md)
=> Testing architecture.

internal/pkg/admission/policy-server-deployment.go
Needed so policy-server can download the up-to-date Fulcio and Rekor
certs to a non read-only path.
Needed by https://github.com/kubewarden/helm-charts/pull/72.
Tested manually as part of https://github.com/kubewarden/helm-charts/pull/72.
=> feat: set KUBEWARDEN_SIGSTORE_CACHE_DIR on deployment

CHANGELOG.md, docs/crds/README.asciidoc
Simple v0.5.1 release containing updated docs/crds and https://github.com/kubewarden/kubewarden-controller/pull/193.
Needed by https://github.com/kubewarden/helm-charts/pull/72.
After this is merged, I will continue with https://github.com/kubewarden/kubewarden-controller/blob/main/CONTRIBUTING.md#push-new-tag-to-the-upstream-repository, tagging and pushing a new tag for GHA to do its things.
=> Sigstore release

.gitignore, Makefile, config/crd/kustomization.yaml
- fix: Disable cert-manager ca injection patches in CRDs
These are not needed; we only need them on the webhooks.
Leaving the patches files themselves, as they are automatically
generated.
- build: Add `make generate-crds` for final CRDs that go to Helm charts
This allows further automation when releasing Helm charts.
Generated crds by manually running `make generate-crds`
=> fix: Disable cert-manager ca injection patches in CRDs

Makefile, config/crd/kustomization.yaml
- fix: Disable conversion webhooks on CRDs, not needed. Thanks @Rafa for realizing!
- build: Create generated-crds dir if doesn't exist.
I thought I did it on the previous pr..
Locally with `make generate-crds`.
=> fix: Disable conversion webhooks on CRDs, not needed

config/rbac/role.yaml, controllers/admissionpolicy_controller.go, controllers/clusteradmissionpolicy_controller.go, controllers/policy_utils.go, controllers/policystatus_utils.go, internal/pkg/constants/constants.go
Updates the code used to check if a policy is unique reachable only when the pods from the last policy server deployment replicaset are ready.
=> Sets policy as isPolicyUniqueReachable when the latest policy pod is ready.

controllers/admissionpolicy_controller_test.go, controllers/clusteradmissionpolicy_controller_test.go, controllers/policy_utils.go
Updates the policy reconciliation loop to set the PolicyActive condition to true when the policy status is updated to "active".
You can test this manually or using the e2e test repository. 
If you want to test it using e2e tests. You need to follow some steps:
```shell
make create-k8s-cluster install-kubewarden basic-e2e-test
```
=> Add PolicyActive condition.

internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/reconciler.go, main.go
Depends on: https://github.com/kubewarden/policy-server/pull/247
This allows the user to configure the controller in a way that when it
reconciles the policy-server deployment, the policy-server will be
configured in a way to always accept requests targeting the namespace
where policy-servers are running (the provided
`--deployments-namespace` argument in the controller)
=> Add `always-accept-admission-reviews-on-deployments-namespace` flag

internal/pkg/admission/policy-server-deployment.go
Updates the env var name used to define the namespace which the policy server should always accept the request.
This PR is necessary after a change done in the review process of the https://github.com/kubewarden/policy-server/pull/247
=> Fix the policy server env var name.

.github/workflows/golangci-lint.yml
This should solve the lint problems for now, but it's not a permanent
solution.
Related to https://github.com/kubewarden/kubewarden-controller/issues/217, but I don't consider it enough to close the card.
=> test: Pin golanci-lint in GHA from latest to 1.45.2

internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/reconciler_test.go, internal/pkg/admission/validating-webhook.go, internal/pkg/admission/webhook_utils.go, internal/pkg/constants/constants.go
Updates the reconciler to add a namespace selector in the webhooks configuration to skip request from the Kubewarden's namespace. Therefore, avoiding issues during the policy server rollout due request being rejected by the old policy server instance.
=> Skip Kubewarden namespace in the webhook configuration.

controllers/admissionpolicy_controller_test.go, controllers/clusteradmissionpolicy_controller_test.go, controllers/policy_utils.go, controllers/policystatus_utils.go
Change the controller to reconcile the policies webhooks and mark the policy as "active" after the policy server rollout.
Fix #209
=> Reconcile webhook after deployment rollout.

.github/workflows/container-build.yml, .github/workflows/container-image.yml
Use cosign keyless to sign the kubewarden-controller image. 
I tested in my fork. You can see the [github actions](https://github.com/raulcabello/kubewarden-controller/actions) and you can verify the signature with:
```
COSIGN_EXPERIMENTAL=1 cosign verify ghcr.io/raulcabello/kubewarden-controller:latest | jq
```
Fix #230
=> feat: sign container image

.golangci.yml
Disable linters that have been deprecated
=> Fix golangci-linter warnings

.github/workflows/e2e-tests.yml, controllers/policystatus_utils.go
Don't skip pods with deletion timestamp in the isUniquelyReachable method
Fix https://github.com/kubewarden/kubewarden-controller/issues/242
=> feat: don't mark policy as uniquely reachable until all terminating pods have disappeared.

.github/workflows/container-build.yml, .github/workflows/container-image.yml, .github/workflows/release.yml
Updates the Github workflow used in our CI pipelines to generate the BOM files and attach it to the container image and add it as an asset in the Github release.
Fix #228
=> feat: Generate Bill Of Materials (BOM) file.

apis/policies/v1/admissionpolicy_webhook.go, apis/policies/v1/clusteradmissionpolicy_webhook.go, apis/policies/v1/policyserver_webhook.go, config/webhook/manifests.yaml
We are converting v1alpha2 resources into v1 using the none conversion strategy
If we add both apiVersions v1 and v1alpha2 to the webhooks we can't create v1alpha2 resources
Removed in the helm charts too https://github.com/kubewarden/helm-charts/pull/103
=> remove v1alpha2 from the webhooks

.github/workflows/container-image.yml, .github/workflows/e2e-tests.yml
Run running the E2E tests is not necessary generate the SBOM file. Therefore, the workflow used to build the container and generate the SBOM file now has a configuration to disable the SBOM file generation.
=> Configuration to disable SBOM generation.

internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-deployment_test.go
Updates the code where the policy server is created to configure the securityContext of the Policy Server container. The process cannot run in a privileged container, cannot run with root user, can run on a read only file system and all the capabilities are dropped.
Fix #203
=> Update policy server security context.

.github/workflows/e2e-tests.yml
Second part of https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/32#discussion_r934788987 for switching to main branch
=> Use main e2e tests branch instead of tag

.github/workflows/golangci-lint.yml, .github/workflows/release.yml, .golangci.yml, apis/policies/v1/webhook_suite_test.go, internal/pkg/admission/policy-server-ca-secret_test.go, internal/pkg/admission/policy-server-configmap.go
This is the offical GH action for releases, and we use it in kwctl and
others.
With this, I hope that release naming will be fixed to
`Release kubewarden-controller v1.1.0`
from
`Release kubewarden-controller refs/tags/v1.1.0`
=> ci: Use actions/create-release

.github/workflows/release.yml, README.md
Adds a new section in the README file and change the SBOM file name attached to the release. This is necessary to improve the project score in the CLO monitor. 
Fix https://github.com/kubewarden/kubewarden-controller/issues/262
=> Change SBOM file names and  adds SBOM section in the README file

.github/workflows/fossa.yml
A fossa scan will be performed when a commit is pushed to main or a new release is created
Fix https://github.com/kubewarden/kubewarden.io/issues/123
=> Add fossa scan

.github/workflows/openssf.yml
Fix https://github.com/kubewarden/kubewarden.io/issues/128
See how badge looks like in the [test project](https://github.com/raulcabello/openssf-test) I created. This is the [github action](https://github.com/raulcabello/openssf-test/actions/runs/3061397214/jobs/4941114158) that triggered the analysis.
I could not use my fork as OpenSSF does not support analyzing forks
=> Add OpenSSF scan to github workflows

.github/workflows/container-build.yml, .github/workflows/release.yml
Run container-build inside of the release workflow, so the release is created after the container image is created.
Release will not be created if container creation failed.
Add container image sbom to the release
[This](https://github.com/raulcabello/kubewarden-controller/releases/tag/vsbomtest18) is how a release looks like
Fix https://github.com/kubewarden/kubewarden-controller/issues/261
Replaces https://github.com/kubewarden/kubewarden-controller/pull/272
=> Run container-build inside of the release workflow and add container image sbom

.github/workflows/openssf.yml
Add missing read-all permissions to openssf scorecard analysis. See [workflow example](https://github.com/ossf/scorecard-action#workflow-example)
Fix https://github.com/kubewarden/kubewarden.io/issues/129
=> Add missing read-all permissions

pkg/apis/policies/v1/admissionpolicy_types.go, pkg/apis/policies/v1/clusteradmissionpolicy_types.go, pkg/apis/policies/v1/policy.go
Add the background audit field to the `Policy` interface. So we can use the `Policy` interface as an abstraction of both `AdmissionPolicy` and `ClusterAdmissionPolicy` in the `audit-scanner` (as we are already doing the `kubewarden-controller`)
=> Add GetBackgroundAudit to Policy interface

CHANGELOG.md
Nothing significant happened, just keep the RC number in sync across the different components of the stack
=> Release v1.3.0-rc2

.github/workflows/container-image.yml
Fix for warning in github action logs
https://github.com/kubewarden/kubewarden-controller/actions/runs/3333531536
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Remove deprecated set-output command

.github/workflows/ci.yml, .github/workflows/container-build.yml, .github/workflows/container-image.yml, .github/workflows/e2e-tests.yml, .github/workflows/fossa.yml, .github/workflows/openssf.yml, .github/workflows/release.yml
Setting token permissions to read-only follows the principle of least privilege. This is important because attackers may use a compromised token with write access to push malicious code into the project. [More info
](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)
This will increase our CLOMonitor score 
Fix https://github.com/kubewarden/kubewarden-controller/issues/333
=> Add read-all permission to all workflows

.github/workflows/container-build.yml, .github/workflows/container-image.yml, .github/workflows/release.yml
Build image gh action was broken when we introduced permissions: read-all at the top level of all files. 
This PR sets the permissions at job level instead, which fixes the issue. This should also be ok with CLOMonitor. We won't get the maximun score for the token permission (10) but it should give us more than 4 that is required for the check to be green. [More info](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)
Everything worked fine when I created a release in my fork with [this changes](https://github.com/raulcabello/kubewarden-controller/actions/runs/3384112138)
=> feat: add permission to each job

.github/workflows/e2e-tests.yml
Add missing permissions for build job.
https://github.com/kubewarden/kubewarden-controller/actions/runs/3406629825/workflow
=> Add write permissions to e2e package build job

apis/policies/v1/admissionpolicy_types.go, apis/policies/v1/clusteradmissionpolicy_types.go, apis/policies/v1/clusteradmissionpolicy_types_test.go, apis/policies/v1/policy.go, internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/validating-webhook.go
There is a problem when the PolicyServer pod is deleted. It can't be recreated because the webhook endpoint points to the PolicyServer which is not available. Error message:
```
Error creating: Internal error occurred: failed calling webhook "clusterwide-do-not-share-host-paths.kubewarden.admission": failed to call webhook: Post "https://policy-server-default.kubewarden.svc:8443/validate/clusterwide-do-not-share-host-paths?timeout=10s": dial tcp 10.100.59.167:8443: connect: connection refused
```
This will prevent any Pod from being created in the cluster. This PR excludes in the webhooks the namespace where Kubewarden was deployed.
Updates will work without doing any extra change. Controller will trigger a reconciliation for each policy the first time it starts. It will find a difference …
=> fix: exclude kubewarden namespace in webhooks

.github/workflows/release.yml
Updates the release CI job to upload the CRDs from the controller as a release asset. Also adds a new step to trigger a CI job in the Helm chart repository to update the Helm charts.
Fix https://github.com/kubewarden/kubewarden-controller/issues/352
=> Upload CRDS and trigger Helm chart update.

docs/crds/README.asciidoc, docs/crds/config.yml
regenerate docs with `docs/crds $ make generate`.
It regenerated them, plus the rendered docs aren't being used right now.
=> docs: Bump docs/crds to k8s 1.25

.github/workflows/release-drafter.yml
Updates the CI release drafter job to be triggered when the a PR is edited. With that, the autolabeler will run when the PR title is changed.
=> Run autolabeler when a PR is edited

.github/release-drafter.yml, .github/workflows/release.yml
Updates the release.yaml workflow file to use the WORKFLOW_PAT token to trigger the Helm chart update. This token is already used for that in past CI jobs.
=> Use WORKFLOW_PAT token to trigger CI.

.github/release-drafter.yml
Adds a new entry in the autolabel configuration to set the label `area/dependencies` when the PR title starts with `build(deps)`
=> Fix release drafter autolabeler

Makefile, apis/policies/v1/admissionpolicy_types.go, apis/policies/v1/admissionpolicy_types_test.go, apis/policies/v1/clusteradmissionpolicy_types.go, apis/policies/v1/clusteradmissionpolicy_types_test.go, apis/policies/v1/policy.go, internal/pkg/admission/policy-server-configmap.go, internal/pkg/admission/policy-server-configmap_test.go, internal/pkg/admission/testing_common.go
Adds the contextAwareResources field in the policies.yml file. This field is added when a ClusterAdmissionPolicy is configured to has access to resource in the cluster setting the `contextAwareResources` field in the policy definition.
Fix #401
=> contextAwareResources field in the policies.yml.

.github/workflows/container-build.yml, .github/workflows/container-image.yml, .github/workflows/release.yml
Cosign 2.0 was [released last week](https://blog.sigstore.dev/cosign-2-0-released/) (yay!) but, as expected because semver, it's not backwards compatible (nay!).
Pin cosign-installer GHA so it downloads cosign 1.*.
Latest [cosign-installer downloads cosign 2.*](https://github.com/sigstore/cosign-installer/releases/tag/v3.0.0).
Tested in other repos.
=> deps: Pin cosign to 1.* by pinning cosign-installer GHA

main.go
fix: Only watch on kubewarden ns for namespaced resources.
This should also improve resource consumption on clusters with a lot of Pods, as we would not be triggering with their changes.
This introduces no changes for cluster-scope resources.
With a controller with this, use rolebinding instead of clusterrolebinding for `kubewarden-controller-manager-cluster-role`.
Everything should still work fine, and the controller logs shouldn't have:
```
*v1.Pod: pods is forbidden: User "system:serviceaccount:kubewarden:kubewarden-controller" cannot list resource "pods" in API group "" at the cluster scope
```
See https://togithub.com/kubernetes-sigs/controller-runtime/blob/main/designs/use-selectors-at-cache.md
See https://togithub.com/kubernetes-sigs/controller-runtime/issues/244
=> fix: Only watch on kubewarden ns for namespaced resources

internal/pkg/admission/policy-server-service.go
The controller is not able to update the policy server service because it always call the create function in the reconciliation loop. Therefore, if the user edits the policy server enabling telemetry, the service will not be updated adding the metric port in the service.
To fix that, this change adds a call to the update function when the creation failed due an "already exists" error.
Fix #432
=> fix: controller failed to update policy server service.

internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-deployment_test.go, internal/pkg/admission/reconciler.go, internal/pkg/constants/constants.go, main.go
Updates the telemetry configuration in all the policy servers by default if the Kubewarden controller has telemetry enabled.
Related to https://github.com/kubewarden/ui/issues/287
=> Set telemetry configuration in policy server deployment.

controllers/policy_utils.go, internal/pkg/admission/reconciler.go
Updates the controller to read the function call to record the policy count metric. It also removes a function not called in the code.
Fix #444 
```shell
kubectl port-forward -n kubewarden --address 0.0.0.0  pod/kubewarden-controller-64f6c5c67b-7jzt9 8080:8080 & 
curl "http://localhost:8080/metrics"                                     
kubewarden_policy_total{failure_policy="",job="unknown_service:manager",module="registry://ghcr.io/kubewarden/policies/pod-privileged:v0.2.2",mutating="false",name="clusterwide-pod-privileged3",namespace="",policy_server="default",policy_status="active"} 37
kubewarden_policy_total{failure_policy="",job="unknown_service:manager",module="registry://ghcr.io/kubewarden/policies/pod-privileged:v0.2.2",mutating="false",name="clusterwide-pod-privileged3",namespace= …
```
=> fix: record policy count metric.

internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-deployment_test.go
The controller was adding the OTEL annotation to inject the collector container in the deploy annotations but it should be added in the pod spec inside the deployment spec. This commit fixes that and the tests to validate this behavior.
=> fix: otel annotations should be in the pod spec.

.github/workflows/container-build.yml, .github/workflows/container-image.yml
Fixes feature branches overwriting `:latest` tag. Now,
- for main branch, build `:latest` tag.
- for feat-foo branch, build `:latest-feat-foo` tag.
Now, don't build `:latest` besides from main or feat-foo branches.
Tested it on my fork, consuming my version of the workflow.
- Build of `:latest` from viccuad/main branch:
https://github.com/viccuad/kubewarden-controller/actions/runs/4935561822/jobs/8822024336
- Build of `:latest-feat-audit`, from viccuad/feat-audit branch:
https://github.com/viccuad/kubewarden-controller/actions/runs/4935576031/jobs/8822055682
https://github.com/viccuad/kubewarden-controller/pkgs/container/kubewarden-controller/92103647?tag=latest-feat-audit
=> ci: Set `image:latest` tag depending on branch name

internal/pkg/admission/policy-server-service.go, internal/pkg/admission/policy-server-service_test.go, internal/pkg/admission/reconciler_test.go
In the latest changes in the controller we remove the need to define the OTEL environment variables in the policy server definition. This causes a problem because the controller uses this information to detect if it should adds the metrics port in the policy server service.
This commit fixes that by checking the flag in the controller to know if metrics are enabled or not.
Related to https://github.com/kubewarden/kubewarden-controller/pull/442
=> fix: missing metrics port in the policy server service.

.github/workflows/release.yml
Updates the step in the release workflow where the helm charts update is trigger to use version tag of the Github action in use, instead of using the commit reference.
=> chore(deps): use version tag instead of commit ref.

pkg/apis/policies/v1/admissionpolicy_types.go, pkg/apis/policies/v1/clusteradmissionpolicy_types.go, pkg/apis/policies/v1/policy.go
Relates to https://github.com/kubewarden/kubewarden-controller/issues/461
feat: Add IsContextAware(), for AdmPolicies returns always false
We are context aware if spec.ContextAwareResources has at least one entry.
AdmissionPolicies cannot be context aware so far.
No test needed.
=> feat: Add IsContextAware(), for AdmPolicies returns always false

.github/workflows/container-build.yml, .github/workflows/container-image.yml, .github/workflows/release.yml
Updates the CI scripts updating the cosign-installer to v3. Thus, the cosign version now is v2. Which has breaking changes requiring some changes on how the command is called and removing the need of using environment variable to enable keyless signature.
Related to https://github.com/kubewarden/kubewarden-controller/issues/411
=> fix: updates cosign to v2.

.github/workflows/container-build.yml, .github/workflows/e2e-tests.yml, .github/workflows/release.yml
Prior to this commit, some GH actions reused workflows that came from the `main` branch, regardless of the branch (or tag) triggering the execution.
This can be a bit dangerous and have side effects. This commit ensures everything stays in sync.
=> fix: GH action, reuse actions from the same checkout

.github/workflows/release.yml
Updates the release CI to check if the pushed tag has some text indicating a release candidate and set properly the flag to 
publish the release as final release or a candidate.
Related to https://github.com/kubewarden/policy-server/pull/497/files#r1268541197
=> fix: enable release candidates when required

.github/workflows/container-build.yml, .github/workflows/container-image.yml, .github/workflows/e2e-tests.yml, .github/workflows/release.yml, .github/workflows/sbom.yml, Dockerfile
Use syft to produce bill or materials of the container image contents and the application itself.
Ensure each architecture-specific build has its own SBOM, signed and attached to the specific image.
Also, attach to the GH release the SBOM of each container image being built.
A preview of the results produced by the this new approach can be found here:
* Push against `main`: [GH run](https://github.com/flavio/kubewarden-controller/actions/runs/5654765398). The run now has a `sbom` artifact, this contains the spdx files and all their signatures
* New tag:
- [GH run](https://github.com/flavio/kubewarden-controller/actions/runs/5655027453). The run failed because it couldn't perform the last release step: triggering the update of helm charts; this fine, since the tag happened inside of a fork …
=> New SBOM generation process

.github/workflows/container-build.yml, .github/workflows/container-image.yml, .github/workflows/release.yml, .github/workflows/sbom.yml, .github/workflows/sign-image.yml
This removes the `id-token` permission from container-image.yml, by separating the image signing into sign-image.yml.
This makes container-image.yml reusable as a workflow. If not, one gets:
```
The nested job 'build' is requesting 'id-token: write', but is only allowed 'id-token: none'
```
This happens on the e2e-tests.yml workflow without this change.
To be tested on my CI fork run. Notice the separation of the container signing into its own job.
Run of build image:
https://github.com/viccuad/kubewarden-controller/actions/runs/5667913267
Run of end-to-end-tests, without the error now:
https://github.com/viccuad/kubewarden-controller/actions/runs/5667954405
(they fail on the e2e tests proper, but not on the build image)
No changes to release job.
=> ci: Fix e2e tests, no need for `id-token` write perms for them

.github/workflows/e2e-tests.yml
This should limit problems with parallel tests on nightly job.
=> Disable schedule tests on forks

.github/workflows/release.yml
This is done by passing `make_latest` in the REST API update. See:
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release
`make_latest` can be `true`, `false`, `legacy`, with legacy using semver, but I'm not sure from where it obtains the semver version (the release name?).
Hence setting it to `true` when not alpha, beta, or rc.
Relates to https://github.com/kubewarden/kubewarden-controller/issues/534.
Not tested.
=> ci: Set normal releases as latest in GH Release page

internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-deployment_test.go, internal/pkg/constants/constants.go
Relates to https://github.com/kubewarden/helm-charts/issues/310
Reconciling this env var means users cannot set it as needed, for example to configure exporters to output JSON.
Not needed.
=> fix!: Don't reconcile KUBEWARDEN_LOG_FMT envvar

internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-deployment_test.go, internal/pkg/admission/reconciler.go, main.go
Related to https://github.com/kubewarden/helm-charts/issues/310
Metrics doesn't set the log format of PolicyServers anymore.
Add logic for enabling tracing when enableTracing is true.
Unit tests.
=> feat!: Add `--enable-tracing`, separate metrics and tracing reconciliation

controllers/admissionpolicy_controller.go, controllers/clusteradmissionpolicy_controller.go, controllers/policyserver_controller.go, internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/validating-webhook.go
Fix https://github.com/kubewarden/kubewarden-controller/issues/224
- feat: Reconcile `{Validating,Mutating}WebhookConfigurations` when they are changed by any other means than our controller. This is done by triggering the policy reconciler, which ends up reconciling the WebhookConfigurations.
- Now, the `{Validating,Mutating}WebhookConfigurations` have an `OwnerReference` that points to their policy.
- The `ownerReferences.blockOwnerDeletion` field is automatically set to true, which means that WebhookConfigurations block the deletion of policy CRDs (see [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications)). This doesn't create any problem, and it's beneficial for us.
- Tested manually, by editing the …
=> feat: Always enforce `{Validating,Mutating}WebhookConfiguration` state

controllers/admissionpolicy_controller.go, controllers/clusteradmissionpolicy_controller.go, controllers/policyserver_controller.go, internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/validating-webhook.go
I've opened this PR to revert the change adding owner reference the webhooks.  This is necessary because the version `v1.9.0-rc2` containing this feature is not able to set the admission policy as active. This is the error from the controller logs:
```
2023-11-01T14:05:06Z    ERROR   Reconciler error        {"controller": "admissionpolicy", "controllerGroup": "policies.kubewarden.io", "controllerKind": "AdmissionPolicy", "AdmissionPolicy": {"name":"pod-privileged","namespace":"kubewarden"}, "namespace": "kubewarden", "name": "pod-privileged", "reconcileID": "cf067c30-e596-4eaa-ae89-91dc683a659e", "error": "error reconciling validating webhook\ncannot set OwnerReference on WebhookConfiguration: cluster-scoped resource must not have a namespace-scoped owner, owner's namespace kubewarden"} …
```
=> Revert "Merge pull request #566 from viccuad/feat-webhooks-reconciled"

.gitignore, CONTRIBUTING.md, Tiltfile, tilt-settings.yaml.example, tilt.dockerfile
This PR is a POC on using Tilt for local development.
It adds a `Tiltfile` on the root of the project, an example settings file, and a Tilt-specific Dockerfile that is used by Tilt to inject the controller in the cluster and auto-reload it when the code changes.
The Tiltfile executes the following steps:
1. Read the `tilt-settings.yaml` file
2. Deploy cert-manager
3. Applys the CRD from the `config/crd` path of the projects. I didn't use the `kubewarden-crds` helm chart here since a developer could be interested in the latest CRD changes while developing.
4. Read the kubewarden controller rendered templates from the helm chart, overriding the image value with one in a private registry (as for now only `ghcr.io` is supported, see the usage section below).
5. Patch the deployment template …
=> chore(dx): use tilt for development

controllers/admissionpolicy_controller_test.go, controllers/clusteradmissionpolicy_controller_test.go, controllers/utils_test.go
Adds assertions checking that the `CABundle` field in webhook configurations has been set correctly by the policy reconcilers.
++
=> test: add CA bundle assertions in webhook configuration subjects

config/crd/bases/policies.kubewarden.io_policyservers.yaml, internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-deployment_test.go, pkg/apis/policies/v1/policyserver_types.go
Relates to https://github.com/kubewarden/helm-charts/pull/361.
Before this, setting the `policyServer.Spec.SecurityContexts.Pod` value would only work on first creation of the Deployment from the PolicyServer CRD (so, on first install of kubewarden-defaults chart for example). With this fix, one can reconfigure the PolicyServers.
Added a unit test.
=> fix: Update SecurityContext of the pod inside of policy-server Deployments

.github/workflows/container-image.yml, .github/workflows/release.yml, .github/workflows/sbom.yml
Upload / download artifact github action are not compatible between v3 and v4. This breaks release job and e2e tests.
Fixes:
- [e2e tests](https://github.com/kubewarden/kubewarden-controller/actions/runs/7333614032/job/19969318246)
- release job
Tested on my fork: https://github.com/kravciak/kubewarden-controller/actions/runs/7337350368/job/19978338359
=> Upgrade artifact upload/download to v4

docs/crds/Makefile
Pin crd-ref-docs binary with new `make crd-ref-docs` target.
This target is adapted from the `make golangci-lint` one in the Makefile on the root project.
Tested by running `make generate` from the docs/crds folder. The target creates a `docs/crds/bin/` folder where it installs the `crd-ref-docs` cli. Which is consumed by `make generate`.
=> deps: Pin crd-ref-docs binary with new `make crd-ref-docs` target

controllers/admissionpolicy_controller.go, controllers/admissionpolicy_controller_test.go, controllers/clusteradmissionpolicy_controller.go, internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/validating-webhook.go
Fix https://github.com/kubewarden/kubewarden-controller/issues/608
Added new test cases to integration tests (instead of adding an upgrade integration testsuite).
Adding integration tests for upgrade scenarios to `controllers/admissionpolicy_controller_test.go` is not trivial. One needs a test that sets up policies and their webhooks manually, and then run the reconciler and check that the webhooks were reconciled correctly, with labels and annotations.
Problem is, We define the unique ginkgo suite in `controllers/suite_test.go/BeforeSuite()`. `BeforeSuite()` runs once before any of the container nodes (the ones with `Describe()`) run. There's no possibility to run anything beforehand, and the k8s env and reconciler is shared between all the container nodes. It's not possible to have more …
=> fix: Initialize nil maps when updating webhooks 

.github/workflows/ci.yml, Makefile, coverage/integration-tests/.gitignore, coverage/unit-tests/.gitignore
Relates to https://github.com/kubewarden/kubewarden-controller/issues/623.
Change makefile targets to save coverage into specific `coverage/{unit-tests,integration-tests}/*` folders.
Add new `codecov.yml` GHA workflow that runs `make test` and uploads the coverage results to codecov via their `codecov` cli.
Tagged unit-tests and integration-tests results separately by setting the codecov flags on the workflow.
Needs a secret `CODECOV_ORG_TOKEN` present, which should be provided by the Codecov GH Application when installed.
To see this working, we need the [Codecov GH application installed in the org,](https://github.com/apps/codecov) and then we will see it working on the next PR opened against the repo.
=> ci: Save coverage files, add codecov workflow

ADOPTERS.md
Added the organization CANCOM to the list of adopters as suggested here: https://github.com/kubewarden/docs/pull/362#issuecomment-1959149662
=> docs: added organization CANCOM

Makefile, controllers/policyserver_controller.go, controllers/policyserver_controller_test.go, controllers/utils_test.go, internal/pkg/admission/reconciler.go, internal/pkg/admission/reconciler_test.go
There is an issue in the policy server controller which is causing inconsistencies when the policy server is deleted. It's possible, due the concurrent nature of events and controllers loops, where the policies ended in a inconsistent state. Where the policy and its webhooks are register in the cluster. But the policy server which should run it is gone. Causing an issue when the control plane tries to contact the policy server.
This is caused because when the policy server controller deletes all the policy server policies, it filters out policies which have the deletion timestamp field. Once no policies are found, in other words, when no policies without deletion timestamp are found, the policy server resources are deleted. However, the deletion timestamp does not ensure that the resource …
=> fix: policy server resource deleted before policies

internal/pkg/admission/policy-server-deployment.go, internal/pkg/admission/policy-server-deployment_test.go
A change has been done to policy-server. Starting from the v1.11 release, the boolean flags must take either `true` or `false` as values when they are toggled via environment variables.
Prior to that, any kind of value was fine.
=> fix: handle enable monitoring boolean flag

Makefile, codecov.yml
Configure codecov to ignore:
- pkg/apis/policies/v1/zz_generated.deepcopy.go
- pkg/apis/policies/v1alpha2
- internal/pkg/constants
Also, sets the project threshold to 1%, meaning that we tolerate a 1% coverage drift comparing the current PR to head.
Fixes: #661
=> chore: configure codecov ignore directive and threshold

controllers/utils_test.go
Increases the integration test timeout that was causing flaky tests
Fixes: #628
=> fix: increase controllers integration test timeout

Makefile
In preparation for the near v1.11.0 release the policy server version used in the tests has been updated to v1.11.0.
=> chore: update policy server version used in tests.

controllers/policyserver_controller_test.go, pkg/apis/policies/v1/policyserver_webhook.go, pkg/apis/policies/v1/policyserver_webhook_test.go
There were some linter errors we did not catch since the Golangci action is acting funny.
For this reason, the PolicyServer controller integration tests were passing even if the expectation was wrong.
I've removed setting requests defaults to limits when the requests are empty to mimic the Kubernetes behavior, which only does this at the Pod level.
=> fix: linter errors and remove requests defaults.

main.go
Removes `Development: true` flag from zap initialization.
=> fix: remove hardcoded zap development option

internal/pkg/admission/mutating-webhook.go, internal/pkg/admission/validating-webhook.go
In a recent change on how we create or update a webhooks the controller started to use the helper function `CreateOrUpdate` to create or update the webhooks. However, the RBAC definition used by the controller allow only to patch the webhooks. Therefore, the controller failed when it trys to update the resources. This commit fixes the issue by using the `CreateOrPatch` helper function instead. The behaviour is the same but it uses the patch verb to "update" the webhooks resources.
Fix #736
=> fix: patch webhooks not update them.

controllers/policyserver_controller_test.go, main.go
Updates the controller configuration to cache ConfigMap resources to avoid too many request to the API server during the reconciliation loops.
Fix #645
=> fix: cache configMap resources.

internal/pkg/admission/policy-server-deployment.go
Prior to this commit, our `CreateOrPatch` function overwrote the Deployment annotations and labels.
This is a problem, because Kubernetes internally uses an annotation to keep track of the Deployment revision.
Because of our behaviour, the controller ended up removing the annotation `deployment.kubernetes.io/revision`. But after a while the Kubernetes reconcilers added it back. Leading to a back and forth between our controller and the Kubernetes ones.
This also manifested itself inside of our e2e tests, which sometimes failed with this message:
> error: desired revision (24) is different from the running revision (0)
The `0` revision is a special value which is assigned by kubectl when the annotation field is NOT found.
This commit prevents annotations and labels to be overwritten. …
=> fix: do not overwrite PolicyServer annotations and labels

Tiltfile
The name of the variable used by the helm chart to replace the system registry was wrong.
That caused tilt to NOT use its own patched image, making everything useless.
=> dev: fix the tilt development file

internal/pkg/admission/policy-server-ca-secret.go, internal/pkg/admission/policy-server-pod-disruption-budget.go, internal/pkg/admission/policy-server-service.go
Consolidate the code to use only `CreateOrPatch` instead of a mix of that and `CreateOrUpdate`
Somehow related with https://github.com/kubewarden/helm-charts/issues/457
=> refactor: use only `CreateOrPatch`

controllers/admissionpolicy_controller_test.go, controllers/clusteradmissionpolicy_controller_test.go, controllers/policy_utils.go, controllers/policyserver_controller.go, controllers/policyserver_controller_test.go, internal/pkg/admission/testing_common.go, internal/pkg/constants/constants.go
Updates the controller to use domain qualified finalizer and follow the best practices. By doing that we fix some warning from the KubeAPI.
Fix #728 
```shell
make tests
```
=> fix: use domain qualified finalizers.

internal/pkg/admissionregistration/cert.go
Bumps policy server TLS cert expiration to 10 years.
=> fix: bump cert NotAfter to 10 years

controllers/admissionpolicy_controller_test.go, controllers/clusteradmissionpolicy_controller_test.go, controllers/policy_utils.go, controllers/policyserver_controller.go, controllers/policyserver_controller_test.go
The finalizer used by the Kubewarden controller is added in the webhook for the policy server and policies types. Therefore, it not needed to add it in the reconciliation loop. Furthermore, the deletion reconciliation is able to handle old finalizer as well. So, this change will not cause issues when deleting resources.
=> fix: its not necessary add the finalizer in the reconciliation loop.

.github/workflows/ci.yml, CONTRIBUTING.md, Makefile, internal/controller/admissionpolicy_controller_test.go, internal/controller/clusteradmissionpolicy_controller_test.go, internal/controller/policyserver_controller_test.go, internal/controller/suite_test.go, internal/controller/utils_test.go
This PR splits the controller tests by using the **fast and slow** testing pattern.
It is now possible to run only certain tests against a real cluster while leveraging the envtest fake 
Tests that need a real cluster to run must now be labeled with `real-cluster`.
See https://onsi.github.io/ginkgo/#spec-labels.
kubernetes API server as the default test environment.
The policy server controller test was refactored to run envtest, which means that some assertions (for instance the ones on the Pod being created) are not possible anymore. However, they are not needed as we are not interested in testing that Kubernetes works.
Also, this PR:
- updates the Makefile to v4, customizing the targets as needed fixing: #786 
- adds `integration-tests-envtest` and `integration-tests-real-cluster` …
=> test: split envtest/real cluster tests

api/policies/v1/policyserver_types.go, internal/controller/policyserver_controller.go, internal/controller/policyserver_controller_ca_secret.go, internal/controller/policyserver_controller_cert_secret.go, internal/controller/policyserver_controller_test.go, internal/controller/utils_test.go
Renames some functions and constants in the code related to CA and certificates reconciliation to avoid confusion.
Fix #782
=> fix: rename some consts and functions.

.github/workflows/ci.yml, Makefile
Adds the ginkgo cli tool dependency to the Makefile, similarly to what Kubebuilder already scaffolds for other external tools.
I've tried to cache the `bin` directory, but restoring the cache takes about the same time as installing the tools from scratch.
=> build: add ginkgo dep to makefile

Tiltfile
After #769 the `Tiltfile` hot reloading configuration needs to be updated
=> fix: tilt hot reloading

.github/workflows/container-build.yml
Introduced with CLOMonitor changes.
See
https://github.com/kubewarden/kubewarden-controller/actions/runs/10352202900/workflow
CI once in main.
=> ci: Fix container-build workflow, no need to set permissions

.github/workflows/container-image.yml
See
https://github.com/kubewarden/kubewarden-controller/actions/runs/10353565242/workflow
Will check when merged on main.
=> ci: Drop unneeded permissions for container-image workflow

Tiltfile, cmd/main.go, internal/certs/certs.go, internal/certs/secrets.go, internal/constants/constants.go, internal/controller/admissionpolicy_controller_test.go, internal/controller/admissionpolicygroup_controller_test.go, internal/controller/cert_controller.go, internal/controller/cert_controller_test.go, internal/controller/clusteradmissionpolicy_controller_test.go, internal/controller/clusteradmissionpolicygroup_controller_test.go, internal/controller/policy_subreconciler.go, internal/controller/policy_subreconciler_webhook.go, internal/controller/policyserver_controller.go, internal/controller/policyserver_controller_cert_secret.go, internal/controller/policyserver_controller_deployment.go, internal/controller/policyserver_controller_test.go, internal/controller/suite_test.go, internal/controller/utils_test.go
This PR introduces a new runnable (`CertController`) that rotates CA root and leaf certificates:
- CA root rotation: see #818
- Server certificate rotation: see #819
It removes the `cert-manager` dependency.
NOTE: this PR requires helm chart changes, see: https://github.com/kubewarden/helm-charts/pull/488
TODO:
The cert controller has been tested by using gingko/envtest.
Before these changes, we used the `kubewarden: true` label in the webhook configuration, to filter kubewarden resources.
However, using the recommended label `app.kubernetes is better.io/part-of` is more idiomatic.
Also, the label is already set by the helm chart on the controller's webhook configurations.
Unfortunately, we need to support both labels to be compatible with the older versions.
There was the need to use the …
=> feat: certificate rotation

Tiltfile
Recently we changed the Tiltfile to override the Helm chart's webhooks with the ones provided by the Kustomize folder.
However, this breaks since we now inject initial certificate bundles from the helm chart.
While having the scaffolded webhooks updated automatically can be handy, we don't expect adding webhooks frequently to justify the added complexity of merging the two configurations.
This PR fixes: #854  by removing the Kustomize webhooks logic in the tiltfile
=> fix(Tiltfile): remove overriding helm webhooks with kustomize ones

config/default/kustomization.yaml
Disable `cert-manager` from scaffolded kustomize config generated by kubebuilder.
Note: the `cert-manager` config directory is still there as it will be generated anyway every time we scaffold a new webhook.
Fixes: #861
=> chore: disable cert-manager from scaffolded kustomize config

Tiltfile, cmd/main.go, internal/constants/constants.go
This reverts commit 0a7941173e5c8e6b42c2a3c15a873aba9c10835a. 
It removes the feature flag added in the past to enable policy group types.
Fix #857
=> Revert "feat: add feature flag for policy groups."

api/policies/v1/admissionpolicy_webhook.go, api/policies/v1/admissionpolicygroup_webhook.go, api/policies/v1/clusteradmissionpolicy_webhook.go, api/policies/v1/clusteradmissionpolicygroup_webhook.go, api/policies/v1/policy_utils_test.go, api/policies/v1/policy_validation.go, api/policies/v1/policy_validation_test.go, api/policies/v1/policygroup_validation.go, api/policies/v1/policygroup_validation_test.go
This PR adds a validation step for the `expression` field of the policy group spec.
An expression must be a valid CEL expression that evaluates to `bool`. Only logic and equality operators are allowed, and policy members are available as functions with zero arity.
It also refactors the policy validation utility functions, cleaning up the existing tests.
Additional cleanup will be needed, which is tracked by: https://github.com/kubewarden/kubewarden-controller/issues/824
Fixes #859
=> feat: validate PolicyGroup expressions

Makefile, api/policies/v1/admissionpolicy_types.go, api/policies/v1/admissionpolicygroup_types.go, api/policies/v1/clusteradmissionpolicy_types.go, api/policies/v1/clusteradmissionpolicy_types_test.go, api/policies/v1/clusteradmissionpolicygroup_types.go, api/policies/v1/policy.go, internal/controller/clusteradmissionpolicy_controller_test.go, internal/controller/clusteradmissionpolicygroup_controller_test.go, internal/controller/policy_subreconciler_webhook.go
The `ClusterAdmissionPolicy` and `ClusterAdmissionPolicyGroup` CRDs were implementing the GetUpdatedNamespaceSelector method from the Policy interface in such a way that each time the getter was invoked, the namespace selector was modified, with a NotIn condition being added to exclude Kubewarden's deployment namespace.
This caused various issues, particularly in packages that imported the CRDs as dependencies, such as the audit-scanner.
This PR removes the namespace exclusion logic from `GetUpdatedNamespaceSelector`, moving it to the policy sub-reconciler. Also, `GetUpdatedNamespaceSelector` was renamed to `GetNamespaceSelector`
=> fix: cluster admission policy and policygroup namspaceSelector getter

api/policies/v1/admissionpolicygroup_types.go, api/policies/v1/clusteradmissionpolicygroup_types.go
This PR fixes the `ClusterAdmissionPolicyGroup` unique name so that it does not conflict with a `ClusterAdmissionPolicy` with the same name.
=> fix: use a different name for ClusterAdmissionpolicyGroup unique name

api/policies/v1/admissionpolicy_types.go, api/policies/v1/admissionpolicygroup_types.go, api/policies/v1/clusteradmissionpolicy_types.go, api/policies/v1/clusteradmissionpolicygroup_types.go, api/policies/v1/policy.go, api/policies/v1/policygroup_validation.go, api/policies/v1/policygroup_validation_test.go, internal/controller/policyserver_controller_configmap.go, internal/controller/policyserver_controller_test.go
=> refactor: split Policy interface and create PolicyGroup interface

api/policies/v1/admissionpolicygroup_webhook.go, api/policies/v1/clusteradmissionpolicygroup_webhook.go, config/webhook/manifests.yaml, internal/controller/policyserver_controller.go
=> fix: policy group plural name

internal/controller/admissionpolicy_controller.go, internal/controller/admissionpolicygroup_controller.go, internal/controller/clusteradmissionpolicy_controller.go, internal/controller/clusteradmissionpolicygroup_controller.go, internal/controller/policy_subreconciler.go
These watches were used a long time ago by the integration tests, they are not needed anymore.
Their removal redeuces the resource usage when running in production.
=> refactor: remove watches used only by integration tests

internal/constants/constants.go, internal/controller/admissionpolicy_controller.go, internal/controller/admissionpolicygroup_controller.go, internal/controller/admissionpolicygroup_controller_test.go, internal/controller/clusteradmissionpolicy_controller.go, internal/controller/clusteradmissionpolicygroup_controller.go, internal/controller/clusteradmissionpolicygroup_controller_test.go, internal/controller/policy_subreconciler.go, internal/controller/policy_subreconciler_webhook.go
This PR adds a group annotation to ValidatingWebhookConfiguration and MutatingWebhookConfiguration for policy groups, enabling us to filter watch requests sent to the respective reconcilers.
=> fix: add group annotation to WebhookConfiguration and filter watch requests 

cmd/main.go
Do not exit with an error when the `matchConditions` field is not available for ValidatingWebhookConfiguration and MutatingWebhookConfiguration.
The code is already structured to work when this feature is not available, hence we don't have to cause the controller to exit with an
error.
Fixes https://github.com/kubewarden/kubewarden-controller/issues/900
=> fix: do not exit when k8s' matchConditions are not available

api/policies/v1/admissionpolicy_types.go, api/policies/v1/admissionpolicygroup_types.go, api/policies/v1/clusteradmissionpolicy_types.go, api/policies/v1/clusteradmissionpolicygroup_types.go, api/policies/v1/policyserver_types.go, api/policies/v1alpha2/admissionpolicy_types.go, api/policies/v1alpha2/clusteradmissionpolicy_types.go, api/policies/v1alpha2/policyserver_types.go, config/crd/bases/policies.kubewarden.io_admissionpolicies.yaml, config/crd/bases/policies.kubewarden.io_admissionpolicygroups.yaml, config/crd/bases/policies.kubewarden.io_clusteradmissionpolicies.yaml, config/crd/bases/policies.kubewarden.io_clusteradmissionpolicygroups.yaml, config/crd/bases/policies.kubewarden.io_policyservers.yaml
Adds shortName for the Kubewarden CRDs. This allows users to get Kubewarden types using acronymous and making the commands smaller to type.
@kubewarden/kubewarden-developers I'm creating this PR as draft because I would like to investigate why `controller-gen` is not updating the CRDs with the `shortNames` for some CRDs. However, I would like to know if you are fine with the proposed `shortNames`. I've prefixed all of them with `k` to flag this is a `kubewarden` resource.
=> feat: shortName for the CRDs.

internal/constants/constants.go, internal/controller/admissionpolicy_controller.go, internal/controller/admissionpolicy_controller_test.go, internal/controller/admissionpolicygroup_controller.go, internal/controller/admissionpolicygroup_controller_test.go, internal/controller/clusteradmissionpolicy_controller.go, internal/controller/clusteradmissionpolicy_controller_test.go, internal/controller/clusteradmissionpolicygroup_controller.go, internal/controller/clusteradmissionpolicygroup_controller_test.go, internal/controller/policy_subreconciler.go, internal/controller/policy_subreconciler_webhook.go
Before this change, we leveraged several annotations to check if a `WebhookConfiguration` was related to the type of policy managed by a controller.
For instance, the `scope` and `group` annotations were used to check if a policy was cluster or namespace scoped and if it was a group. 
When adding `PolicyGroups` we realized that it was hard to maintain multiple annotations.
This PR simplifies the `WebhookConfiguration` controller handlers, by using just two annotations (`name` and `namespace`) ~and by using the client to check if the resource of a certain type exists.
This is ok regarding performance and API server load since the request is cached.~
and returning a reconcile request.
=> refactor: simplify wehbook configuration controller handlers

.github/ISSUE_TEMPLATE/kubewarden-release.yml
Adds an issue template with the base checklist needed to properly release a Kubewarden version.
This is an [example](https://github.com/jvanz/kubewarden-controller/issues/31) of the issue submitted with no change in the form filled by the user.
This is inspired by https://github.com/kubewarden/community/pull/29
=> chore: Kubewarden release issue template.

Tiltfile, cmd/main.go, internal/controller/policy_subreconciler.go, internal/controller/policyserver_controller.go, internal/controller/policyserver_controller_deployment.go, internal/metrics/metrics.go, tilt-settings.yaml.example
Updates the collector to allow the communication with a remote OpenTelemetry collector. Also updates the policy server reconciler to replicate the same configuration in the policy server deployment enabling it to send data to the same remote Otel collector.
Fix #933 
> [!WARNING]  
> This PR was tested together with the changes from [this](https://github.com/kubewarden/helm-charts/pull/581) Helm chart changes
Create a simple cluster with required dependencies:
```
k3d cluster create 
helm repo add jetstack https://charts.jetstack.io --force-update
helm upgrade -i --wait cert-manager jetstack/cert-manager \
-n cert-manager --create-namespace \
--set crds.enabled=true
helm repo add --force-update open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm upgrade -i …
```
=> Remote otel collector configuration

Makefile
Ensure the ginkgo binary version matches with the one inside of `go.mod`
=> chore(deps): update ginkgo binary

Makefile, internal/controller/policyserver_controller_configmap.go, internal/controller/policyserver_controller_test.go, internal/controller/utils_test.go
The "url" field used in the policy server configuration configmap has been renamed to "module". This ensures that the name used in the configmap follow the same name used in the CRDs.
Fix https://github.com/kubewarden/policy-server/issues/906
```shell
make POLICY_SERVER_VERSION=issue906 POLICY_SERVER_REPOSITORY=ghcr.io/jvanz/policy-server test e2e-tests
```
Needs to be tested together with https://github.com/kubewarden/policy-server/pull/1016
=> fix: rename "url" field into "module".

internal/controller/admissionpolicy_controller_test.go, internal/controller/admissionpolicygroup_controller_test.go, internal/controller/clusteradmissionpolicy_controller_test.go, internal/controller/clusteradmissionpolicygroup_controller_test.go, internal/controller/factories_test.go, internal/controller/policyserver_controller_test.go, internal/controller/utils_test.go
Creates builders to allow dynamic object building during tests.
Part of #824 
@kubewarden/kubewarden-developers this is one of a series of PR open to refactor the webhooks tests. This is a initial change to use builder pattern to build (hehe) test objects. This is not a 100% convertion. But it's a start to see if you are all  fine with the current changes before the next one following the same idea.
=> feat(test): use builder to build test objects.

api/policies/v1/policy_validation.go, api/policies/v1/policy_validation_test.go, config/crd/bases/policies.kubewarden.io_policyservers.yaml
By design, AdmissionPolicy and AdmissionPolicyGroup can evaluate only namespaced resources. The resources to be evaluated are determined by the `rules` provided by the user.
There might be Kubernetes namespaced resources that should not be validated by AdmissionPolicy and AdmissionPolicyGroup policies because of their sensitive nature.
For example, PolicyReport are namespaced resources that contain the list of non compliant objects found inside of a namespace.
Prior to this commit, an AdmissionPolicy or an AdmissionPolicyGroup could prevent the creation of PolicyReports. Moreover, a mutating AdmissionPolicy could even alter the contents of the PolicyReports created inside of the namespace.
This commit extends the validation rules applied to AdmissionPolicy and AdmissionPolicyGroup to …
=> fix: stricter checks on AdmissionPolicy and AdmissionPolicyGroup rules

go.mod, go.sum
To keep the cel-go dependency aligned with the version used in apiserver, we need to downgrade it to that same version and mark it as indirect.
This change is necessary to stop the bot from automatically updating the dependency, as was observed in #983.
**Note:** This wasn't done by simply adding the indirect dependency to the go.mod file. Instead, I removed the dependency and then re-added it using `go get github.com/google/cel-go@v0.22.0`.
=> build(deps): move cel-go dependecy to indirect

go.mod, renovate.json
We should align the `cel-go` version with the one used in `k8s.io/apiserver`. Since `cel-go` is a direct dependency, a replace directive is required, and the Renovate bot should exclude it from updates
.
=> build(deps): disable cel-go bot updates 

cmd/main.go, internal/constants/constants.go, internal/controller/admissionpolicy_controller_test.go, internal/controller/admissionpolicygroup_controller_test.go, internal/controller/clusteradmissionpolicy_controller_test.go, internal/controller/clusteradmissionpolicygroup_controller_test.go, internal/controller/policyserver_controller.go, internal/controller/policyserver_controller_deployment.go, internal/controller/policyserver_controller_test.go, internal/controller/suite_test.go, internal/controller/utils_test.go
This PR introduces the `--client-ca-config-map` flag.  
When specified, the setup function configures the webhook server with the client CA.  
Additionally, it mounts the ConfigMap in the reconciled PolicyServer deployments and sets the `KUBEWARDEN_CLIENT_CA_FILE` environment variable to the CA path.
Fix: #993
=> feat: add mTLS support

cmd/main.go
Fixes the client-ca file path to align with the server certificate location of the webhook server. Since Kubernetes does not allow a ConfigMap volume mount for client-ca to share the same path as the TLS certificates Secret, a subpath is used instead.
=> fix: client-ca filepath

Makefile, api/policies/v1/policyserver_types.go, internal/constants/constants.go, internal/controller/policyserver_controller_configmap.go, internal/controller/policyserver_controller_deployment.go, internal/controller/policyserver_controller_pdb.go, internal/controller/policyserver_controller_service.go, internal/controller/policyserver_controller_test.go
All the resources associated with Policy Server are now using the labels recommended by Kubernetes, see [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels).
=> policy server use kubernetes recommended labels

Tiltfile, tilt-settings.yaml.example
Do not configure the registry that holds the development image of kubewarden-controller as the place from which all the images of the `kubewarden-controller` helm chart have to be pulled from. This would cause the deployment to fail, since all the other images (like kubectl, audit-scanner) are not mirrored on the local registry.
Instead, patch the image attribute of the Deployment.
Add the ability to set labels of the `kubewarden` namespace created by Tilt. This allows to test different PSA profiles and tune our deployment.
=> dev: fix tilt environment

api/policies/v1/policyserver_types.go
Closes kubewarden/docs#565
This PR fixes a broken link to Kubernetes annotations documentation on the [CRDs reference page](https://docs.kubewarden.io/reference/CRDs).
Updated the link in go docstring from https://kubernetes.io/docs/user-guide/annotations to https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
=> fixed crd annotations link in go docstring

Makefile, api/policies/v1/policyserver_types.go, internal/constants/constants.go, internal/controller/policyserver_controller_deployment.go, internal/controller/policyserver_controller_pdb.go, internal/controller/policyserver_controller_service.go, internal/controller/utils_test.go
> **WARNING:** do not merge
This PR builds on top of https://github.com/kubewarden/kubewarden-controller/pull/1037/ and it must be merged a couple of releases after 1.23 is out.
This PR removes the old non-standard labels used by Policy Server. In certain cases it replaces them using the recommended Kubernetes labels.
We cannot merge this PR right now because we could cause a downtime during a Kubewarden upgrade.
With the 1.23 release all the Policy Server workloads will have the old and the new labels set.
With the 1.24+ release, the Policy Server workloads will have only the new labels. The Policy Server Service will use only the new labels inside of its selector.
However, we don't know how quickly the new workloads (the only using only the new labels) will be rolled out by Kubernetes. …
=> policy server remove non standard labels

api/policies/v1/policyserver_types.go, internal/constants/constants.go, internal/controller/policyserver_controller_deployment.go
Revert the change removing the "app" label from the policy server deployment. This label will be removed in future policy lifecycle refactoring. The label is also marked as deprecated
Fix #1081 
This is a spin-off https://github.com/kubewarden/kubewarden-controller/pull/1084#issuecomment-2809692577
E2e tests using this branch container image:
```console
make CONTROLLER_ARGS="--set image.tag=issue1081-app-label-deploy --set image.repository=jvanz/kubewarden-controller"  clean cluster install tests
```
Controller tests:
```
make tests
```
=> fix: keep "app" label in the policy server deployment

internal/constants/constants.go
Fix https://github.com/kubewarden/kubewarden-controller/issues/1104
Revert the change that set a valid domain for the PolicyServerLabelKey, instead of just `kubewarden`, as this would make upgrades break without further reconciler changes.
This label is used to tie Pods, ConfigMaps, Services with a specific PolicyServer by the controller, and will be removed in future policy lifecycle refactoring.
E2E tests.
=> refactor(policy-server): Keep old policy-server label key

.github/workflows/ci.yml
Updates the golang linter used in the CI workflow to v2.1.0.
Required to make the CI [here](https://github.com/kubewarden/kubewarden-controller/pull/1117) happy.
=>  chore: updates golang linter.

api/policies/v1/policyserver_types.go, config/crd/bases/policies.kubewarden.io_policyservers.yaml, docs/crds/CRD-docs-for-docs-repo.adoc, docs/crds/CRD-docs-for-docs-repo.md, internal/controller/policyserver_controller_deployment.go, internal/controller/policyserver_controller_test.go
Fix https://github.com/kubewarden/kubewarden-controller/issues/1077
Add new optional PolicyServer.spec.PriorityClassName, and update the CRD definitions.
If the PolicyServer.spec.PriorityClassName is not set (or is an empty string), Kubernetes will not assign a PriorityClass and the Pods will inherit the default priority (behaviour prior to this change).
Added a new unit test which checks that the `spec.PriorityClassName` is correctly used when set.
=> feat: Add new optional PolicyServer.spec.PriorityClassName
